### ISSUE TITLE
Reading Order model integration simplification

### ISSUE THREAD

**Issue by mllife** [huridocs/pdf-document-layout-analysis#91]
Hello, I want to continue the discussion from here - https://huggingface.co/HURIDOCS/pdf-reading-order/discussions/1

Thanks for all of your work, I am exploring to integrate your code into my project but, need more simplification.
Any way to do this without Poppler and do this with some other pdf parsing framework. Is it possible for you to modularise part where its extract pdf stuff and then make a separate code specifically for adding results from segment model and all the other stuff into a pipeline for easy integration with different backbones for parsing. Or just make input as simple as list of segments in a page {contained text, bbox of segment, type of segment} and output as dict{bbox: order}; <did i miss anything else required?>

please share a sample jupyter notebook.
regards.

**Comment by gabriel-piles** [comment]
Thank you for your valuable suggestion. We understand the importance of interchangeability for the parser and appreciate your insight.

While making this change would require a significant time investment, it's not currently a top priority due to our ongoing commitments to supporting NGOs in other areas. However, we recognize the potential benefits and encourage you to explore this feature by creating a fork of the project.

The codebase is already structured to facilitate this change, particularly within the PdfFeatures class and its initialization. With some additional effort, you should be able to implement the interchangeable parser functionality in a repository fork.
