### ISSUE TITLE
Tables recognition

### ISSUE THREAD

**Issue by gbanusi** [huridocs/pdf-document-layout-analysis#92]
The app works pretty well on most documents, but on some it just says everything is a table:

![image](https://github.com/user-attachments/assets/832d4c97-87af-42b8-9056-9484bc7723b8)

Is there any idea how to reprocess the tables?

**Comment by gabriel-piles** [comment]
Hi! 

We saw some errors as well, and we believe they can be fixed with more labeled data. However, we are currently focusing our time on other areas that require our attention. The training set we are using is not ours. It is called DocLayNet and is a human-annotated document layout segmentation dataset containing 80,863 pages from a broad variety of document sources.

Can you try both models (fast and slow) for this page and share your results with us?

curl -X POST -F 'file=@/PATH/TO/PDF/pdf_name.pdf' -F "fast=true" localhost:5060
curl -X POST -F 'file=@/PATH/TO/PDF/pdf_name.pdf' -F "fast=false" localhost:5060

Thank you very much.

**Comment by gbanusi** [comment]
I'll try it out and let you know! :)

**Comment by gabriel-piles** [comment]
Thank you for your suggestion.

 It is not possible for us to decide which model is correct for each PDF page. We will think about this.

In our overall results, the VGT model (default model) is better on average and it detects images properly, something that the fast model is not capable of.
